### ISSUE TITLE
sh 脚本获取 Hardware Port 名称时，如果名称是用空格分开的话（就像图中的），就获取不到完整的名称，这样获取 DNS 和设置 DNS 都会失败 经测试把名称中间的空格去掉就行了

### ISSUE THREAD

**Issue by vitaminc55** [clash-verge-rev/set-dns-script#3]
sh 脚本获取 Hardware Port 名称时，如果名称是用空格分开的话（就像图中的），就获取不到完整的名称，这样获取 DNS 和设置 DNS 都会失败
经测试把名称中间的空格去掉就行了
![IMG_20240505_103406](https://github.com/clash-verge-rev/set-dns-script/assets/164356692/a7ae2d22-bd83-42e4-90ec-dca19b6a7d85)
问了一下 ai，改成这样就可以了
hardware_port=$(networksetup -listallhardwareports | awk -v dev="$nic" -F': ' '/Hardware Port/{port=$2} /Device:/{if ($2 == dev) {gsub(/ /,"",port); print port; exit}}')

**Comment by NahidaBuer** [comment]
遇到了同样的问题。只不过我是用USB网卡的，路径也有空格。不过给出的代码好像有点问题…

解决后大概长这样
```shell
nic=$(route -n get default | grep "interface" | awk '{print $2}')

hardware_port=$(networksetup -listallhardwareports | awk -v dev="$nic" '
    /Hardware Port:/{
        port=$0; gsub("Hardware Port: ", "", port)
    } 
    /Device: /{
        if ($2 == dev) {
            print port; 
            exit
        }
    }
')

original_dns=$(networksetup -getdnsservers "$hardware_port")

if [ ${#original_dns} -gt 15 ]
then
    echo "Empty" > original_dns.txt
else
    echo $original_dns > original_dns.txt
fi

networksetup -setdnsservers "$hardware_port" 223.5.5.5
```

**Comment by vitaminc55** [comment]
不知道你测试过这段代码没有，我试了一下，确实可以获取正确的名称，但设置 DNS 会出错，系统不能识别带空格的 hardware port 名称，就像图中的报错信息
![Uploading IMG_20240510_170004.png…]()
